---
role_name_check: 1
driver:
  name: docker
platforms:
  # - name: debian-11
  #   image: debian:11
  #   pre_build_image: false
  #   dockerfile: ../docker-files/Dockerfile.debian.j2
  # - name: debian-12
  #   image: debian:12
  #   pre_build_image: false
  #   dockerfile: ../docker-files/Dockerfile.debian.j2
  - name: instance
    image: "${MOLECULE_IMAGE:-debian:12}"
    pre_build_image: false
    dockerfile: ../docker-files/Dockerfile.${MOLECULE_DISTRO-debian}.j2

provisioner:
  name: ansible
  inventory:
      host_vars:
        ansible_user: globus
